### ISSUE TITLE
bones.page.id

### ISSUE THREAD

**Issue by warwickbuilds** [oldrivercreative/SPComments#1]
This solution looks really good in theory, just trying to test it out, where are you setting and pull all the bones. references from?

**Comment by warwickbuilds** [comment]
![image](https://user-images.githubusercontent.com/12653520/29872552-4125795c-8dcf-11e7-935f-1a678c45106a.png)

For everyone's reference I updated all the bones references to the attached image and everything works except for the REST POST calls, they return a 200 successful message but a comment/reply/edit is never updated in the list.

**Comment by warwickbuilds** [comment]
I had no Idea what pagePhysical was trying to reference, so I just get it to the name name, I'm using web part connections so i'm show all comments logged against that ID rather than a page, and it works great.

**Comment by kyleschaeffer** [comment]
Sorry, we should have been more clear about that – bones refers to the "bones.js" utility method available in our SPBones starter template. You can copy this file from that project, here:
https://github.com/oldrivercreative/spbones/blob/master/resources/js/bones.js

**Comment by warwickbuilds** [comment]
No worries at all, really appreviate you sharing this solution, really slick! Really enjoy all the content you've put out on the web and youtube, though wish you website was still up, lots of links and references still point there.

I'll try referencing that bones.js and see if it resolves the successful REST post but nothing showing in the list.
